services:
  - type: web
    name: jumptake
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_DEMO_PREMIUM_PRICE_ID
        sync: false
      - key: STRIPE_PREMIUM_PRICE_ID
        sync: false
      - key: STRIPE_EXTREME_PRICE_ID
        sync: false
