const JOB_INTEREST_OPTIONS = [
    'Software Engineering',
    'Frontend Development',
    'Backend Development',
    'Data Analysis',
    'Artificial Intelligence',
    'Cybersecurity',
    'Product Management',
    'Project Management',
    'Marketing',
    'Sales',
    'Finance',
    'Human Resources',
    'Healthcare',
    'Education',
    'Customer Support',
    'Design',
    'Operations',
    'Business Analysis',
    'Cloud Engineering',
    'Quality Assurance',
    'DevOps Engineering',
    'Mobile App Development',
    'UI/UX Design',
    'Graphic Design',
    'Data Science',
    'Machine Learning',
    'Database Administration',
    'Network Engineering',
    'IT Support',
    'Solutions Architecture',
    'Technical Writing',
    'Legal Services',
    'Accounting',
    'Banking',
    'Insurance',
    'Real Estate',
    'Construction',
    'Architecture',
    'Mechanical Engineering',
    'Electrical Engineering',
    'Civil Engineering',
    'Manufacturing',
    'Supply Chain',
    'Logistics',
    'Procurement',
    'Hospitality',
    'Tourism',
    'Food and Beverage',
    'Retail',
    'E-commerce',
    'Media and Communications',
    'Public Relations',
    'Content Writing',
    'Social Media Management',
    'Research',
    'Science and Laboratory',
    'Environmental Services',
    'Agriculture',
    'Public Service',
    'Nonprofit and Charity'
];

export default JOB_INTEREST_OPTIONS;
